name: VisionUtils
version: '${version}'
main: visionUtils.Plugin
api-version: 1.18
commands:
  skip:
    usage: /skip [accept | decline]
    description: Startet eine Abstimmung über das Skippen der Nacht